config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #adminモデルのルーティング(url path・ヘルパーメソッドController#Action)をusersで指定
  namespace :admin do
    resources :users
  end
  root to: 'tasks#index'
  resources :tasks
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    
    before_validation :set_nameless_name

    #名前が存在するかしないかを検証する
    validates :name, presence: true
    #30文字以内かどうかを検証する
    validates :name, length: { maximum: 30 }
    
    #:以下をvalidate(クラスメソッド)に渡すことでTaskモデルにこのメソッドは検証のために利用するということを伝える
    validate :validate_name_not_including_comma
    
    #外部キーとしてuserを抱えていることを定義
    belongs_to :user
    #タスクの作成日時を降順にする
    scope :recent, -> { order(created_at: :desc)}


    #オブジェクトの外部から呼び出さないためprivateメソッドを使用する
    private
    
    def set_nameless_name
        self.name = '名前無し' if name.blank?
    end
    def validate_name_not_including_comma
    #errors.addでエラー内容を格納する
    #&.(ぼっち演算子)を入れることでnilでもエラーを吐かずnilのままif文を通過する
        errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
    end
end

app/models/user.rb
class User < ApplicationRecord
    #passwordとpassword_confirmationを使えるようにする
    has_secure_password
    #空データを保存できないようにする
    validates :name, presence: true
    #データが重複しないようにする
    validates :email, presence: true, uniqueness: true
    #外部キーが複数個あることを定義(tasks)
    has_many :tasks
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  #ユーザーの一覧画面
  def index
    #Userテーブルの情報を全て取得して@usersに格納
    @users = User.all
  end

  #ユーザーの詳細画面
  def show
    #Userテーブルの中からidが一致する情報を探して@userに格納
    @user = User.find(params[:id])
  end

  #ユーザーの新規登録画面
  def new
    #インスタンスを作成
    @user = User.new
  end


  #ユーザーの編集画面
  def edit
    #paramsに格納したidと一致する情報をUseモデルの中から探して@userに格納
    @user = User.find(params[:id])
  end

  #登録アクション
  def create
    #ユーザーの登録情報を格納したものを@userに代入
    @user = User.new(user_params)
    #＠userが保存できる(空のカラムが無い)とき
    if @user.save
    #admin_users_pathに移動
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
    #新規登録画面を再び表示する
      render :new
    end
  end
  
  #更新を行う
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice:'ユーザー「#{@user.name}」を更新しました。'
    else
      render :new
    end
  end
  
  #削除を行う
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー"
  end
  
private
  #もし管理者権限がなかった場合トップ画面にリダイレクトする
  def require_admin
    redirect_to root_path unless current_user.admin?
  end

  def user_params
    #送られてきた情報をuserテーブルのnameモデル以下として取得する
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #current_userをヘルパーメソッドに指定する
    helper_method :current_user
    before_action :login_required

    private

    #もしsession[:user_id]があるとき(ログインしているとき)ユーザー情報を取得してcurrent_userインスタンスに格納
    def current_user
        #(||=) current_userに何も格納されていない時代入
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def login_required
        redirect_to login_path unless current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  #ログインフォーム画面(GET)
  def new
  end

  #フォームから送られてきた情報をもとにログインする(POST)
  def create
    #session_paramsに格納した情報のうちメールアドレスを取得しUserテーブルのemailカラムと一致するメールアドレスを検索する
    user = User.find_by(email: session_params[:email])
    #authanticateメソッドでパスワード認証が通ったとき
          #has_secure_passwordで使えるようになる
          #&.でuserがnilの時'nil'を返してエラー回避
    if user&.authenticate(session_params[:password])
    #sessionにuser_idを格納
      session[:user_id] = user.id
    #
      redirect_to root_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    #セッション情報を削除
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end

  private
  #送られてきたセッションのemailカラムとpasswordカラムの情報を取得する
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #privateメソッドのset_taskアクションを[]内に適用
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  #タスク一覧画面
  def index
    #ログインしているユーザーに紐づくタスクのみ表示
    @tasks = current_user.tasks
  end

  #タスク詳細画面
  def show
    #ログインしているユーザーに紐づくタスクのみ表示
    #@task = current_user.tasks.find(params[:id])
  end
  
  #新規作成画面
  def new
    @task = Task.new
  end
  
  #タスク登録画面
  def create
      #task_paramsメソッドを引数にしてインスタンスを作成することでデータを引き継いで表示する
    @task = current_user.tasks.new(task_params)
      #条件分岐をするためsaveではなくsave!を使う
    if @task.save
      #一覧画面にリダイレクトする
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      #newページ(登録用フォーム画面)を再び表示
      render :new
    end
  end
  
  #タスクの編集画面
  def edit
    #@task = current_user.tasks.find(params[:id])
  end
  
  #タスクの更新
  def update
    #task = current_user.tasks.find(params[:id])
    @task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
  end
  
  #タスクの削除
  def destroy
    #task = current_user.tasks.find(params[:id])
    @task.destroy
    redirect_to tasks_url, notice: "タスク「#{task.name}」を削除しました。"
  end
  

  private
  
  def task_params
    #taskテーブルのname,descriptionモデルを変更
    params.require(:task).permit(:name, :description)
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
    ul#error_explanation
        - user.errors.full_messages.each do |message|
        li= message

= form_with model: [:admin, user], local: true do |f|
    .form-group
        = f.label :name, '名前'
        = f.text_field :name, class: 'form-control'
    
    .form-group
        = f.label :email, 'メールアドレス'
        = f.text_field :email, class: 'form-control'
    .form-check
        = f.label :admin, class: 'form-check-label' do
            = f.check_box :admin, class: 'form-check-input'
        | 管理者権限
    .form-group
        = f.label :password, 'パスワード'
        = f.password_field :password, class: 'form-control'
    .form-group
        = f.label :password_confirmation, 'パスワード(確認)'
        = f.password_field :password_confirmation, class: 'form-control'
    = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集
.nav.justify-content-end 
    = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3 
table.table.table-hover
    thread.thread-default 
        tr 
            th = User.human_attribute_name(:name)
            th = User.human_attribute_name(:email)
            th = User.human_attribute_name(:admin)
            th = User.human_attribute_name(:create_at)
            th = User.human_attribute_name(:update_at)
            th
    tbody
        - @users.each do |user|
            tr 
                td = link_to user.name, [:admin, user]
                td = user.email 
                td = user.admin? ? 'あり' : 'なし'
                td = user.created_at 
                td = user.updated_at 
                td 
                    = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
                    = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end 
    = link_to '一覧', admin_users_path, class: 'nav-link'

//_form.html.slimファイルからrenderする
= render partial: 'form', locals: { user: @user}

app/views/admin/users/show.html.slim
h1 ユーザの詳細

.nav.justify-content-end
    = link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
    tbody
        tr
            th= User.human_attribute_name(:id)
            td= @user.id
        tr
            th= User.human_attribute_name(:name)
            td= @user.name
        tr
            th= User.human_attribute_name(:email)
            td= @user.email
        tr
            th= User.human_attribute_name(:admin)
            td= @user.admin? ? 'あり' : 'なし'
        tr
            th= User.human_attribute_name(:created_at)
            td= @user.created_at
        tr
            th= User.human_attribute_name(:updated_at)
            td= @user.updated_at

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザ「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Taskleaf
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Taskleaf

      ul.navbar-nav.ml-auto
        /current_userが存在するとき(ログインしているとき)
        - if current_user
          /タスク一覧のリンク
          li.nav-item= link_to 'タスク一覧', tasks_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'

    .container
      - if flash.notice.present?
        .alert.alert-sucsess= flash.notice
      = yield


    
    

app/views/tasks/_form.html.slim
/検証エラーの有無を調べエラーがあるときにはエラーメッセージを表示
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li= message

= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', tasks_path, class:'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.slim
h1 タスク一覧
=link_to '新規登録', new_task_path, class:'btn btn-primary'

.mp-3
table.table.table-hover
  thread.thread-default
    tr
      th= Task.human_attribute_name(:name)
      th= Task.human_attribute_name(:created_at)
      th
  tbody
    - @tasks.each do |task|
      tr
        td= link_to task.name, task
        td= task.created_at
        td
          = link_to '編集', edit_task_path(task), class:'btn btn-primary mr-3'
          = link_to '削除', task, method: :delete, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
  =link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }
  

app/views/tasks/show.html.slim
h1 タスクの詳細


.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th = Task.human_attribute_name(:id)
      td = @task.id
    tr
      th = Task.human_attribute_name(:name)
      td = @task.name
    tr
      th = Task.human_attribute_name(:description)
      td = simple_format(h(@task.description), {}, sanitize: false, wrapper_tag:"div")
    tr
      th = Task.human_attribute_name(:created_at)
      td = @task.created_at
    tr
      th = Task.human_attribute_name(:updated_at)
      td = auto_link(simple_format(h(@task.description),{},sanitize: false, wrapper_tag: "div"))

= link_to '編集', edit_task_path, class:'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'